name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸ New features available'
    label: 'ğŸ feature'
  - title: 'ğŸ Bug fixes'
    label: 'ğŸ”¨ fix'
  - title: 'ğŸ¬ Code improvements'
    label:
      - 'ğŸ“‹ docs'
      - 'ğŸ§¼ refactor'
      - 'ğŸª„ setting'
      - 'ğŸ« test'
      - 'ğŸš€ deploy'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Changes in this version
  ---
  $CHANGES
no-changes-template: 'No changes available'
version-resolver:
  major:
    labels:
      - 'âœ¨ major'
  minor:
    labels:
      - 'âœ¨ minor'
  patch:
    labels:
      - 'âœ¨ patch'
  default: 'patch'